- name: Configure Server
  hosts: all
  become: yes
  tasks:
    - name: Update and install dependencies
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes
